### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by bocan** [arturscheiner/kuberverse#6]
Is there some particular technical reason you're building this with 4 year old Xenial instead of Focal?  Or is that just your personal preference?

With just a few simple changes, it seems to build with Focal and I'm about to test it shortly.

**Comment by arturscheiner** [comment]
The reason why I left this way was because to take the official certifications exams from Linux Foundation, candidates should prepare themselfs, preferably, on an environment as close as the real and proctored test, as possible. When I started this, I was studying to take the CKA and CKAD certifications and, at the time, they used ubuntu 16.04 in their exam environment. They used this version up to early this year (2020) when I take my CKA. Now, with the introduction of exams based on kubernetes 1.19 the test environment is using ubuntu 18.04. I will update the labs sooner to reflect 18.04, but you can try it with newer images.
